// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/DHSerializedData.proto

public final class DHSerializedData {
  private DHSerializedData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublicKeyEncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PublicKeyEnc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes encodedPublicKey = 1;</code>
     * @return A list containing the encodedPublicKey.
     */
    java.util.List<com.google.protobuf.ByteString> getEncodedPublicKeyList();
    /**
     * <code>repeated bytes encodedPublicKey = 1;</code>
     * @return The count of encodedPublicKey.
     */
    int getEncodedPublicKeyCount();
    /**
     * <code>repeated bytes encodedPublicKey = 1;</code>
     * @param index The index of the element to return.
     * @return The encodedPublicKey at the given index.
     */
    com.google.protobuf.ByteString getEncodedPublicKey(int index);
  }
  /**
   * Protobuf type {@code PublicKeyEnc}
   */
  public static final class PublicKeyEnc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PublicKeyEnc)
      PublicKeyEncOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublicKeyEnc.newBuilder() to construct.
    private PublicKeyEnc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublicKeyEnc() {
      encodedPublicKey_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PublicKeyEnc();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PublicKeyEnc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                encodedPublicKey_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              encodedPublicKey_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          encodedPublicKey_ = java.util.Collections.unmodifiableList(encodedPublicKey_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DHSerializedData.internal_static_PublicKeyEnc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DHSerializedData.internal_static_PublicKeyEnc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DHSerializedData.PublicKeyEnc.class, DHSerializedData.PublicKeyEnc.Builder.class);
    }

    public static final int ENCODEDPUBLICKEY_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> encodedPublicKey_;
    /**
     * <code>repeated bytes encodedPublicKey = 1;</code>
     * @return A list containing the encodedPublicKey.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getEncodedPublicKeyList() {
      return encodedPublicKey_;
    }
    /**
     * <code>repeated bytes encodedPublicKey = 1;</code>
     * @return The count of encodedPublicKey.
     */
    public int getEncodedPublicKeyCount() {
      return encodedPublicKey_.size();
    }
    /**
     * <code>repeated bytes encodedPublicKey = 1;</code>
     * @param index The index of the element to return.
     * @return The encodedPublicKey at the given index.
     */
    public com.google.protobuf.ByteString getEncodedPublicKey(int index) {
      return encodedPublicKey_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < encodedPublicKey_.size(); i++) {
        output.writeBytes(1, encodedPublicKey_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < encodedPublicKey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(encodedPublicKey_.get(i));
        }
        size += dataSize;
        size += 1 * getEncodedPublicKeyList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DHSerializedData.PublicKeyEnc)) {
        return super.equals(obj);
      }
      DHSerializedData.PublicKeyEnc other = (DHSerializedData.PublicKeyEnc) obj;

      if (!getEncodedPublicKeyList()
          .equals(other.getEncodedPublicKeyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEncodedPublicKeyCount() > 0) {
        hash = (37 * hash) + ENCODEDPUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getEncodedPublicKeyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DHSerializedData.PublicKeyEnc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DHSerializedData.PublicKeyEnc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DHSerializedData.PublicKeyEnc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DHSerializedData.PublicKeyEnc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DHSerializedData.PublicKeyEnc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PublicKeyEnc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PublicKeyEnc)
        DHSerializedData.PublicKeyEncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DHSerializedData.internal_static_PublicKeyEnc_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DHSerializedData.internal_static_PublicKeyEnc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DHSerializedData.PublicKeyEnc.class, DHSerializedData.PublicKeyEnc.Builder.class);
      }

      // Construct using DHSerializedData.PublicKeyEnc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        encodedPublicKey_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DHSerializedData.internal_static_PublicKeyEnc_descriptor;
      }

      @java.lang.Override
      public DHSerializedData.PublicKeyEnc getDefaultInstanceForType() {
        return DHSerializedData.PublicKeyEnc.getDefaultInstance();
      }

      @java.lang.Override
      public DHSerializedData.PublicKeyEnc build() {
        DHSerializedData.PublicKeyEnc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DHSerializedData.PublicKeyEnc buildPartial() {
        DHSerializedData.PublicKeyEnc result = new DHSerializedData.PublicKeyEnc(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          encodedPublicKey_ = java.util.Collections.unmodifiableList(encodedPublicKey_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.encodedPublicKey_ = encodedPublicKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DHSerializedData.PublicKeyEnc) {
          return mergeFrom((DHSerializedData.PublicKeyEnc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DHSerializedData.PublicKeyEnc other) {
        if (other == DHSerializedData.PublicKeyEnc.getDefaultInstance()) return this;
        if (!other.encodedPublicKey_.isEmpty()) {
          if (encodedPublicKey_.isEmpty()) {
            encodedPublicKey_ = other.encodedPublicKey_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEncodedPublicKeyIsMutable();
            encodedPublicKey_.addAll(other.encodedPublicKey_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DHSerializedData.PublicKeyEnc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DHSerializedData.PublicKeyEnc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> encodedPublicKey_ = java.util.Collections.emptyList();
      private void ensureEncodedPublicKeyIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          encodedPublicKey_ = new java.util.ArrayList<com.google.protobuf.ByteString>(encodedPublicKey_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @return A list containing the encodedPublicKey.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEncodedPublicKeyList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(encodedPublicKey_) : encodedPublicKey_;
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @return The count of encodedPublicKey.
       */
      public int getEncodedPublicKeyCount() {
        return encodedPublicKey_.size();
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @param index The index of the element to return.
       * @return The encodedPublicKey at the given index.
       */
      public com.google.protobuf.ByteString getEncodedPublicKey(int index) {
        return encodedPublicKey_.get(index);
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @param index The index to set the value at.
       * @param value The encodedPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setEncodedPublicKey(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodedPublicKeyIsMutable();
        encodedPublicKey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @param value The encodedPublicKey to add.
       * @return This builder for chaining.
       */
      public Builder addEncodedPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodedPublicKeyIsMutable();
        encodedPublicKey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @param values The encodedPublicKey to add.
       * @return This builder for chaining.
       */
      public Builder addAllEncodedPublicKey(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEncodedPublicKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, encodedPublicKey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodedPublicKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncodedPublicKey() {
        encodedPublicKey_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PublicKeyEnc)
    }

    // @@protoc_insertion_point(class_scope:PublicKeyEnc)
    private static final DHSerializedData.PublicKeyEnc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DHSerializedData.PublicKeyEnc();
    }

    public static DHSerializedData.PublicKeyEnc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicKeyEnc>
        PARSER = new com.google.protobuf.AbstractParser<PublicKeyEnc>() {
      @java.lang.Override
      public PublicKeyEnc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PublicKeyEnc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublicKeyEnc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicKeyEnc> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DHSerializedData.PublicKeyEnc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EncodedParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EncodedParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes encodedParams = 1;</code>
     * @return A list containing the encodedParams.
     */
    java.util.List<com.google.protobuf.ByteString> getEncodedParamsList();
    /**
     * <code>repeated bytes encodedParams = 1;</code>
     * @return The count of encodedParams.
     */
    int getEncodedParamsCount();
    /**
     * <code>repeated bytes encodedParams = 1;</code>
     * @param index The index of the element to return.
     * @return The encodedParams at the given index.
     */
    com.google.protobuf.ByteString getEncodedParams(int index);
  }
  /**
   * Protobuf type {@code EncodedParams}
   */
  public static final class EncodedParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EncodedParams)
      EncodedParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EncodedParams.newBuilder() to construct.
    private EncodedParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EncodedParams() {
      encodedParams_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EncodedParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EncodedParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                encodedParams_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              encodedParams_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          encodedParams_ = java.util.Collections.unmodifiableList(encodedParams_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DHSerializedData.internal_static_EncodedParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DHSerializedData.internal_static_EncodedParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DHSerializedData.EncodedParams.class, DHSerializedData.EncodedParams.Builder.class);
    }

    public static final int ENCODEDPARAMS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> encodedParams_;
    /**
     * <code>repeated bytes encodedParams = 1;</code>
     * @return A list containing the encodedParams.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getEncodedParamsList() {
      return encodedParams_;
    }
    /**
     * <code>repeated bytes encodedParams = 1;</code>
     * @return The count of encodedParams.
     */
    public int getEncodedParamsCount() {
      return encodedParams_.size();
    }
    /**
     * <code>repeated bytes encodedParams = 1;</code>
     * @param index The index of the element to return.
     * @return The encodedParams at the given index.
     */
    public com.google.protobuf.ByteString getEncodedParams(int index) {
      return encodedParams_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < encodedParams_.size(); i++) {
        output.writeBytes(1, encodedParams_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < encodedParams_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(encodedParams_.get(i));
        }
        size += dataSize;
        size += 1 * getEncodedParamsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DHSerializedData.EncodedParams)) {
        return super.equals(obj);
      }
      DHSerializedData.EncodedParams other = (DHSerializedData.EncodedParams) obj;

      if (!getEncodedParamsList()
          .equals(other.getEncodedParamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEncodedParamsCount() > 0) {
        hash = (37 * hash) + ENCODEDPARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getEncodedParamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DHSerializedData.EncodedParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.EncodedParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.EncodedParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DHSerializedData.EncodedParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DHSerializedData.EncodedParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DHSerializedData.EncodedParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DHSerializedData.EncodedParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EncodedParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EncodedParams)
        DHSerializedData.EncodedParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DHSerializedData.internal_static_EncodedParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DHSerializedData.internal_static_EncodedParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DHSerializedData.EncodedParams.class, DHSerializedData.EncodedParams.Builder.class);
      }

      // Construct using DHSerializedData.EncodedParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        encodedParams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DHSerializedData.internal_static_EncodedParams_descriptor;
      }

      @java.lang.Override
      public DHSerializedData.EncodedParams getDefaultInstanceForType() {
        return DHSerializedData.EncodedParams.getDefaultInstance();
      }

      @java.lang.Override
      public DHSerializedData.EncodedParams build() {
        DHSerializedData.EncodedParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DHSerializedData.EncodedParams buildPartial() {
        DHSerializedData.EncodedParams result = new DHSerializedData.EncodedParams(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          encodedParams_ = java.util.Collections.unmodifiableList(encodedParams_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.encodedParams_ = encodedParams_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DHSerializedData.EncodedParams) {
          return mergeFrom((DHSerializedData.EncodedParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DHSerializedData.EncodedParams other) {
        if (other == DHSerializedData.EncodedParams.getDefaultInstance()) return this;
        if (!other.encodedParams_.isEmpty()) {
          if (encodedParams_.isEmpty()) {
            encodedParams_ = other.encodedParams_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEncodedParamsIsMutable();
            encodedParams_.addAll(other.encodedParams_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DHSerializedData.EncodedParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DHSerializedData.EncodedParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> encodedParams_ = java.util.Collections.emptyList();
      private void ensureEncodedParamsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          encodedParams_ = new java.util.ArrayList<com.google.protobuf.ByteString>(encodedParams_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @return A list containing the encodedParams.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getEncodedParamsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(encodedParams_) : encodedParams_;
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @return The count of encodedParams.
       */
      public int getEncodedParamsCount() {
        return encodedParams_.size();
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @param index The index of the element to return.
       * @return The encodedParams at the given index.
       */
      public com.google.protobuf.ByteString getEncodedParams(int index) {
        return encodedParams_.get(index);
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @param index The index to set the value at.
       * @param value The encodedParams to set.
       * @return This builder for chaining.
       */
      public Builder setEncodedParams(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodedParamsIsMutable();
        encodedParams_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @param value The encodedParams to add.
       * @return This builder for chaining.
       */
      public Builder addEncodedParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEncodedParamsIsMutable();
        encodedParams_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @param values The encodedParams to add.
       * @return This builder for chaining.
       */
      public Builder addAllEncodedParams(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureEncodedParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, encodedParams_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes encodedParams = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncodedParams() {
        encodedParams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EncodedParams)
    }

    // @@protoc_insertion_point(class_scope:EncodedParams)
    private static final DHSerializedData.EncodedParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DHSerializedData.EncodedParams();
    }

    public static DHSerializedData.EncodedParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EncodedParams>
        PARSER = new com.google.protobuf.AbstractParser<EncodedParams>() {
      @java.lang.Override
      public EncodedParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EncodedParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EncodedParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EncodedParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DHSerializedData.EncodedParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CiphertextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ciphertext)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes ciphertext = 1;</code>
     * @return A list containing the ciphertext.
     */
    java.util.List<com.google.protobuf.ByteString> getCiphertextList();
    /**
     * <code>repeated bytes ciphertext = 1;</code>
     * @return The count of ciphertext.
     */
    int getCiphertextCount();
    /**
     * <code>repeated bytes ciphertext = 1;</code>
     * @param index The index of the element to return.
     * @return The ciphertext at the given index.
     */
    com.google.protobuf.ByteString getCiphertext(int index);
  }
  /**
   * Protobuf type {@code Ciphertext}
   */
  public static final class Ciphertext extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ciphertext)
      CiphertextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ciphertext.newBuilder() to construct.
    private Ciphertext(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ciphertext() {
      ciphertext_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Ciphertext();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ciphertext(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ciphertext_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              ciphertext_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ciphertext_ = java.util.Collections.unmodifiableList(ciphertext_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DHSerializedData.internal_static_Ciphertext_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DHSerializedData.internal_static_Ciphertext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DHSerializedData.Ciphertext.class, DHSerializedData.Ciphertext.Builder.class);
    }

    public static final int CIPHERTEXT_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> ciphertext_;
    /**
     * <code>repeated bytes ciphertext = 1;</code>
     * @return A list containing the ciphertext.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getCiphertextList() {
      return ciphertext_;
    }
    /**
     * <code>repeated bytes ciphertext = 1;</code>
     * @return The count of ciphertext.
     */
    public int getCiphertextCount() {
      return ciphertext_.size();
    }
    /**
     * <code>repeated bytes ciphertext = 1;</code>
     * @param index The index of the element to return.
     * @return The ciphertext at the given index.
     */
    public com.google.protobuf.ByteString getCiphertext(int index) {
      return ciphertext_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ciphertext_.size(); i++) {
        output.writeBytes(1, ciphertext_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ciphertext_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(ciphertext_.get(i));
        }
        size += dataSize;
        size += 1 * getCiphertextList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DHSerializedData.Ciphertext)) {
        return super.equals(obj);
      }
      DHSerializedData.Ciphertext other = (DHSerializedData.Ciphertext) obj;

      if (!getCiphertextList()
          .equals(other.getCiphertextList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCiphertextCount() > 0) {
        hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getCiphertextList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DHSerializedData.Ciphertext parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.Ciphertext parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DHSerializedData.Ciphertext parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DHSerializedData.Ciphertext parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DHSerializedData.Ciphertext parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DHSerializedData.Ciphertext parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DHSerializedData.Ciphertext prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ciphertext}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ciphertext)
        DHSerializedData.CiphertextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DHSerializedData.internal_static_Ciphertext_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DHSerializedData.internal_static_Ciphertext_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DHSerializedData.Ciphertext.class, DHSerializedData.Ciphertext.Builder.class);
      }

      // Construct using DHSerializedData.Ciphertext.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ciphertext_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DHSerializedData.internal_static_Ciphertext_descriptor;
      }

      @java.lang.Override
      public DHSerializedData.Ciphertext getDefaultInstanceForType() {
        return DHSerializedData.Ciphertext.getDefaultInstance();
      }

      @java.lang.Override
      public DHSerializedData.Ciphertext build() {
        DHSerializedData.Ciphertext result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DHSerializedData.Ciphertext buildPartial() {
        DHSerializedData.Ciphertext result = new DHSerializedData.Ciphertext(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          ciphertext_ = java.util.Collections.unmodifiableList(ciphertext_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ciphertext_ = ciphertext_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DHSerializedData.Ciphertext) {
          return mergeFrom((DHSerializedData.Ciphertext)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DHSerializedData.Ciphertext other) {
        if (other == DHSerializedData.Ciphertext.getDefaultInstance()) return this;
        if (!other.ciphertext_.isEmpty()) {
          if (ciphertext_.isEmpty()) {
            ciphertext_ = other.ciphertext_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCiphertextIsMutable();
            ciphertext_.addAll(other.ciphertext_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DHSerializedData.Ciphertext parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DHSerializedData.Ciphertext) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> ciphertext_ = java.util.Collections.emptyList();
      private void ensureCiphertextIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ciphertext_ = new java.util.ArrayList<com.google.protobuf.ByteString>(ciphertext_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @return A list containing the ciphertext.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getCiphertextList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(ciphertext_) : ciphertext_;
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @return The count of ciphertext.
       */
      public int getCiphertextCount() {
        return ciphertext_.size();
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @param index The index of the element to return.
       * @return The ciphertext at the given index.
       */
      public com.google.protobuf.ByteString getCiphertext(int index) {
        return ciphertext_.get(index);
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @param index The index to set the value at.
       * @param value The ciphertext to set.
       * @return This builder for chaining.
       */
      public Builder setCiphertext(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCiphertextIsMutable();
        ciphertext_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @param value The ciphertext to add.
       * @return This builder for chaining.
       */
      public Builder addCiphertext(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCiphertextIsMutable();
        ciphertext_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @param values The ciphertext to add.
       * @return This builder for chaining.
       */
      public Builder addAllCiphertext(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureCiphertextIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ciphertext_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ciphertext = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCiphertext() {
        ciphertext_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Ciphertext)
    }

    // @@protoc_insertion_point(class_scope:Ciphertext)
    private static final DHSerializedData.Ciphertext DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DHSerializedData.Ciphertext();
    }

    public static DHSerializedData.Ciphertext getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ciphertext>
        PARSER = new com.google.protobuf.AbstractParser<Ciphertext>() {
      @java.lang.Override
      public Ciphertext parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ciphertext(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ciphertext> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ciphertext> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DHSerializedData.Ciphertext getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicKeyEnc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicKeyEnc_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EncodedParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EncodedParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ciphertext_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ciphertext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/java/DHSerializedData.proto\"(" +
      "\n\014PublicKeyEnc\022\030\n\020encodedPublicKey\030\001 \003(\014" +
      "\"&\n\rEncodedParams\022\025\n\rencodedParams\030\001 \003(\014" +
      "\" \n\nCiphertext\022\022\n\nciphertext\030\001 \003(\014b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublicKeyEnc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublicKeyEnc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicKeyEnc_descriptor,
        new java.lang.String[] { "EncodedPublicKey", });
    internal_static_EncodedParams_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EncodedParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EncodedParams_descriptor,
        new java.lang.String[] { "EncodedParams", });
    internal_static_Ciphertext_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Ciphertext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ciphertext_descriptor,
        new java.lang.String[] { "Ciphertext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
